# Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# Binaries
brew "readline"
brew "sqlite"
brew "xz"
brew "autojump"
brew "azure-cli"
brew "brew-cask-completion"
brew "python@3.9"
brew "docker-compose"
brew "doctl"
brew "geos"
brew "gdal"
brew "htop"
brew "kubernetes-cli"
brew "mas"
brew "minikube"
brew "netcat"
brew "openssl@3"
brew "pipenv"
brew "proj"
brew "psqlodbc"
brew "pyenv"
brew "pyenv-virtualenv"
brew "terraform"
brew "tldr"
brew "virtualenv"
brew "zlib"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"

# Apps
cask "docker"
cask "go2shell"
cask "iterm2"
cask "lens"
cask "microsoft-auto-update"
cask "microsoft-azure-storage-explorer"
cask "microsoft-office"
cask "multipass" # Ubuntu VM
cask "notable"
cask "postman"
cask "pycharm"
cask "spotify"
cask "stack"
cask "teamviewer"
cask "telegram"
cask "vanilla"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"

# App Store apps
mas 634148309 # Logic Pro x